### ISSUE TITLE
combine hdf5 tests into fewer executables

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#111]
...to reduce compile times. the google test framework and boost PP should be able to do that fairly efficiently, rather than having CMake generate all of the types.

**Comment by egull** [comment]
done.

**Comment by galexv** [comment]
Compilation problems in commit 06936597 can probably be fixed by adding a couple of `typename`. Just have compiled it successfully with gcc, trying clang now...

**Comment by egull** [comment]
clang works. Trying intel now...

**Comment by egull** [comment]
Yep, intel works. I think this is closed.

**Comment by aeantipov** [comment]
Do we still have an ExtendedTests flag for hdf5_io_tests? It's runtime is 2 min.
